- name: Build Caddy
  block:
    - name: Copy CaddyFile
      template:
        src: "{{ 'files/origin/caddy/Caddyfile' if inventory_hostname in groups['origin'] else 'files/edge/caddy/Caddyfile.j2' }}"
        dest: /root/containers/Caddyfile
      when: inventory_hostname in groups['origin'] or inventory_hostname in groups['edge']

    - name: Create caddy logs folder
      file:
        path: /root/containers/caddyLogs
        state: directory