- name: Build Caddy
  block:
    - name: Copy configuration files
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop: >
        {{ [
            { 'src': 'files/origin/caddy/Caddyfile', 'dest': '/root/containers/Caddyfile' },
            { 'src': 'files/origin/varnish/default.vcl.j2', 'dest': '/root/containers/default.vcl' },
          ] if inventory_hostname in groups['origin'] else
          [
            { 'src': 'files/edge/varnish/default.vcl.j2', 'dest': '/root/containers/default.vcl' },
            { 'src': 'files/edge/caddy/Caddyfile.j2', 'dest': '/root/containers/Caddyfile' },
          ] }}

    - name: Create caddy logs folder
      file:
        path: /root/containers/caddyLogs
        state: directory