- name: Add GlusterFS repository key
  apt_key:
    url: "https://download.gluster.org/pub/gluster/glusterfs/9/rsa.pub"
    state: present

- name: Add GlusterFS repository
  apt_repository:
    repo: "deb https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/{{ ansible_distribution_major_version }}/amd64/apt {{ ansible_distribution_release }} main"
    state: present

- name: Set default value for current_auth_allow_ips
  set_fact:
    current_auth_allow_ips: ""

# Check if the 'origin' group is empty
- name: Check if origins group is empty
  set_fact:
    origins_empty: "{{ groups['origin'] | length == 0 }}"
  run_once: true

# Gather all edge IPs
- name: Gather all edge IPs
  set_fact:
    all_edge_ips: "{{ groups['edge'] | map('extract', hostvars, ['ansible_host']) | join(',') }}"
  when: origins_empty

# Retrieve the current auth.allow list for GlusterFS volume from all origins
- name: Get current auth.allow list for GlusterFS volume from all origins
  delegate_to: "{{ item }}"
  command: gluster volume get cert_vol auth.allow
  register: current_auth_allow
  changed_when: false
  loop: "{{ origin_ips }}"
  when: 
    - origins_empty
    - (inventory_hostname in groups["edge"] or inventory_hostname in groups["origin"])

# Extract auth.allow IPs
- name: Extract auth.allow IPs
  set_fact:
    current_auth_allow_ips: "{{ current_auth_allow.results | map(attribute='stdout_lines') | flatten | select('match', '^auth.allow[ \t]+') | map('regex_replace', '^auth.allow[ \t]+', '') | list | first }}"
  when: 
    - origins_empty
    - current_auth_allow is defined
    - current_auth_allow.results | length > 0

# Append new edge IPs to the existing auth.allow list
- name: Append new edge IPs to auth.allow list
  set_fact:
    updated_auth_allow_ips: "{{ (current_auth_allow_ips.split(',') + all_edge_ips.split(',')) | unique | select('match', '^[^,].*[^,]$') | join(',') }}"
  when: origins_empty

- name: Set updated auth.allow for input origin IPs
  delegate_to: "{{ item }}"
  command:
    cmd: "gluster volume set cert_vol auth.allow '{{ updated_auth_allow_ips }}'"
  loop: "{{ origin_ips }}"
  when: origins_empty and inventory_hostname in groups['edge']
  register: result
  until: result is succeeded
  retries: 5
  delay: 10  # This will introduce a 10-second delay between retries


# Only edges in inventory
- name: Install GlusterFS client on edges
  apt:
    name: glusterfs-client
    state: present
    update_cache: yes
  when: inventory_hostname in groups["edge"]

# Only origins tasks
- name: Configure GlusterFS for origin nodes
  block:
    ## All origins
    - name: Install GlusterFS server on origins
      apt:
        name: glusterfs-server
        state: present
        update_cache: yes
      
    - name: Enable and start glusterd service
      systemd:
        name: glusterd
        enabled: true
        state: restarted
        daemon_reload: yes

    - name: Create brick directory
      file:
        path: /etc/ssl/caddy
        state: directory
        owner: root
        group: root
        mode: '0755'

    ## Only on first origin
    - name: First Origin configuration for GlusterFS
      block:
        - name: Check if GlusterFS volume exists
          command: gluster volume info cert_vol
          register: volume_info
          failed_when: false
          changed_when: false
          when: inventory_hostname in groups["origin"]

        - name: Get list of peers from each origin
          command: gluster peer status
          register: peer_status
          failed_when: false
          changed_when: false
          when: inventory_hostname in groups["origin"]   

        - name: Check current GlusterFS peers
          command: gluster peer status
          register: gluster_peers
          failed_when: false
          changed_when: false
          when: inventory_hostname in groups["origin"]

        - name: Configure GlusterFS peers
          command: gluster peer probe {{ hostvars[item]['ansible_host'] }}
          when: 
            - inventory_hostname in groups["origin"]
            - hostvars[item]['ansible_host'] not in gluster_peers.stdout
          with_items: "{{ groups['origin'][1:] }}"
          loop_control:
            pause: 5
          when: 
            - inventory_hostname in groups["origin"]
            - hostvars[item]['ansible_host'] not in peer_status.stdout

        - name: Create GlusterFS volume
          command: >
            gluster volume create cert_vol
            {% if groups['origin'] | length > 1 %}
            replica {{ groups['origin'] | length }}
            {% endif %}
            transport tcp
            {% for host in groups['origin'] %}
            {{ hostvars[host]['ansible_host'] }}:/etc/ssl/caddy
            {% endfor %}
            force
          when: 
            - inventory_hostname in groups["origin"]
            - "'Volume Name: cert_vol' not in volume_info.stdout"

        - name: Set auth.allow for GlusterFS volume
          command: >
            gluster volume set cert_vol auth.allow "{{ ((groups['origin'] | map('extract', hostvars, 'ansible_host') | list) + (groups['edge'] | map('extract', hostvars, 'ansible_host') | list)) | join(',') }}"
          register: result
          until: result is succeeded
          retries: 5
          delay: 10
          run_once: true
          delegate_to: "{{ groups['origin'][0] }}"
          when: 
            - inventory_hostname in groups["origin"]
            - "'Volume Name: cert_vol' in volume_info.stdout"

        - name: Start GlusterFS volume
          command: gluster volume start cert_vol
          when: 
            - inventory_hostname in groups["origin"]
            - "'Volume Name: cert_vol' in volume_info.stdout"
            - "'Status: Started' not in volume_info.stdout"


  when: inventory_hostname in groups["origin"]


- name: Prepare to mount GlusterFS volume on all nodes
  set_fact: 
    primary_origin_server: "{{ origin_ips[0] }}"
    backup_origin_servers: "{{ origin_ips[1:] | join(',') }}"
    mount_point: /root/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/

- name: Set mount options based on group membership
  set_fact:
    mount_opts: "{{ 'defaults,_netdev' + (',backup-volfile-servers=' + backup_origin_servers if groups['origin'] | length > 1 else '') }}"
  when: inventory_hostname in groups['edge'] or inventory_hostname in groups['origin']


- name: Check if GlusterFS volume is mounted
  shell: mountpoint -q "{{ mount_point }}"
  register: is_mounted
  failed_when: false
  changed_when: false

- name: Clear mount point just in case
  file:
    state: absent
    path: "{{ mount_point }}"
  when: is_mounted.rc != 0

- name: Create mount point
  file:
    path: "{{ mount_point }}"
    state: directory
    owner: root
    group: root
    mode: '0755'


- name: Get current auth.allow list for GlusterFS volume from all origins
  delegate_to: "{{ item }}"
  command: gluster volume get cert_vol auth.allow
  register: current_auth_allow
  changed_when: false
  loop: "{{ origin_ips }}"
  when: inventory_hostname in groups["edge"] or inventory_hostname in groups["origin"]

- name: Extract auth.allow IPs
  set_fact:
    current_auth_allow_ips: "{{ current_auth_allow.stdout_lines[-1] | regex_replace('^auth.allow[ \t]+', '') }}"
  when: 
    - current_auth_allow is defined
    - "'stdout_lines' in current_auth_allow"
    - current_auth_allow.stdout_lines is not none
    - current_auth_allow.stdout_lines | length > 0


- name: Gather all edge IPs
  set_fact:
    all_edge_ips: "{{ groups['edge'] | map('extract', hostvars, ['ansible_host']) | join(',') }}"


- name: Set auth.allow for each origin
  delegate_to: "{{ item }}"
  command:
    cmd: "gluster volume set cert_vol auth.allow {{ all_edge_ips }}"
  loop: "{{ groups['origin'] }}"
  when: inventory_hostname in groups['edge']
  register: result
  until: result is succeeded
  retries: 5
  delay: 10  # This will introduce a 10-second delay between retries
  

- name: Mount GlusterFS volume using primary server
  command:
    cmd: "mount -t glusterfs {{ item }}:/cert_vol /root/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/"
  loop: "{{ groups['origin'] | map('extract', hostvars, 'ansible_host') | list }}"
  when: 
    - inventory_hostname in groups['edge']
    - is_mounted.rc != 0


- name: Add GlusterFS volume to /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "{{ primary_origin_server }}:/cert_vol {{ mount_point }} glusterfs {{ mount_opts }} 0 0"
    state: present
    create: yes
  when: 
    - volume_info is defined
    - "'stdout' in volume_info"
    - "'Volume Name: cert_vol' in volume_info.stdout"


