- name: Mount GlusterFS volume using primary server with unlimited retries
  command: >
    mount -t glusterfs {{ item }}:/cert_vol /root/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/
  loop: "{{ groups['origin'] | map('extract', hostvars, 'ansible_host') | list }}"
  when: 
    - inventory_hostname in groups['edge']
    - is_mounted.rc != 0
  retries: 5  # Set retries to a very high number
  delay: 5   # Adjust the delay between retries as needed
  until: mount_result is succeeded
  register: mount_result


- name: Add GlusterFS volume to /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "{{ primary_origin_server }}:/cert_vol {{ mount_point }} glusterfs {{ mount_opts }} 0 0"
    state: present
    create: yes
  when: 
    - volume_info is defined
    - "'stdout' in volume_info"
    - "'Volume Name: cert_vol' in volume_info.stdout"