- include: set_facts.yml
- include: system.yml
- include: postgres.yml
  when: inventory_hostname in groups["origin"]
- include: varnish.apt.yml
- include: caddy.yml
- include: stats.yml
- include: gluster.yml
- include: optimize.yml
- include: nodejs.yml
- include: origin.yml
  when: inventory_hostname in groups["origin"]
- include: edge.yml
  when: inventory_hostname in groups["edge"]
# - include: origin2.yml
#   when: inventory_hostname in groups["origin"]
- include: ganache.yml
  when: inventory_hostname in groups["origin"] and testing == true