- include: set_facts.yml
- include: system.yml
- include: postgres.yml
  when: inventory_hostname in groups["origin"]
- include: varnish.apt.yml
- include: caddy.yml
- include: stats.yml
- include: gluster.yml
- include: optimize.yml
- include: origin.yml
  when: inventory_hostname in groups["origin"]
