- include_tasks: set_facts.yml
- include_tasks: system.yml
- include_tasks: gluster.yml
- include_tasks: optimize.yml
- include_tasks: docker.yml
- include_tasks: caddy-docker.yml
- include_tasks: varnish-docker.yml
- include_tasks: stats-docker.yml
- include_tasks: docker-origin.yml
  when: inventory_hostname in groups["origin"]
- include_tasks: docker-edge.yml
  when: inventory_hostname in groups["edge"]
- include_tasks: start-origin.yml
  when: inventory_hostname in groups["origin"]
- include_tasks: start-edge.yml
  when: inventory_hostname in groups["edge"]
