- name: Configure Linux system settings
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - { name: fs.file-max, value: 999999 }
    - { name: fs.inotify.max_user_watches, value: 999999 }
    - { name: fs.inotify.max_user_instances, value: 999999 }
    - { name: net.ipv4.tcp_fin_timeout, value: 30 }
    - { name: net.core.somaxconn, value: 65535 }
    - { name: net.core.netdev_max_backlog, value: 65535 }
    - { name: net.ipv4.ip_local_port_range, value: "15000 61000" }

- name: Configure systemd settings
  ini_file:
    path: "{{ item.path }}"
    section: DefaultLimitNOFILE
    option: DefaultLimitNOFILE
    value: 999999
    state: present
  loop:
    - { path: /etc/systemd/system.conf }
    - { path: /etc/systemd/user.conf }

- name: Set the system's maximum open file limit
  shell: ulimit -n 999999
  changed_when: false
