- name: Remove existing origin
  file:
    path: /root/origin
    state: absent

- name: Create program directory
  file:
    path: /root/origin
    state: directory

- name: Copy program folder
  synchronize:
    src: ../origin/
    dest: /root/origin
    rsync_opts:
      - "--exclude=node_modules/"
      - "--exclude=yarn.lock"
      - "--exclude=.git"

- name: Create env.ts file
  template:
    src: files/origin/config/env.ts.j2
    dest: /root/origin/config/env.ts

- name: Create networks.ts file
  template:
    src: files/origin/config/networks.ts.j2
    dest: /root/origin/config/networks.ts

- name: Run yarn install in program folder
  command: yarn install
  args:
    chdir: /root/origin/

- name: Copy ecosystem file for pm2
  copy:
    src: files/origin/pm2/ecosystem.config.js
    dest: /root/
    follow: no

- name: Start pm2 from ecosystem
  command:
    cmd: 'pm2 start ecosystem.config.js'
    chdir: /root/

- name: pm2 startup for restart
  command:
    cmd: 'pm2 startup'

- name: pm2 save
  command:
    cmd: 'pm2 save'

- name: Create /var/www/challenges directory
  file:
    path: /var/www/challenges
    state: directory
    owner: "root"
    group: "root"
    mode: 0755