- name: Remove existing origin
  file:
    path: /root/origin
    state: absent

- name: Remove existing abis
  file:
    path: /root/media-evm-abis
    state: absent

- name: Create program directory
  file:
    path: /root/origin
    state: directory

- name: Copy program folder
  copy:
    src: ../origin/
    dest: /root/origin

- name: Copy abis folder
  copy:
    src: ../media-evm-abis/
    dest: /root/media-evm-abis

- name: Create .env file
  copy:
    dest: "/root/origin/config/env.js"
    content: |
      module.exports = {
        WALLET: "{{wallet_address}}",
        PRIVATE_KEY: "{{private_key}}",
        dbstring: "postgres://origin:{{postgres_password.user_input}}@127.0.0.1:5432/origin",
        caddyUrl: "http://127.0.0.1:2020/",
        host: "medianetwork.app", // dev
        hns: "medtv", // dev
      }

- name: Run yarn install in program folder
  command: yarn install
  args:
    chdir: /root/origin/

- name: Copy ecosystem file for pm2
  ansible.builtin.copy:
    src: files/origin/pm2/ecosystem.config.js
    dest: /root/
    follow: no

- name: Start pm2 from ecosystem
  command:
    cmd: 'pm2 start ecosystem.config.js'
    chdir: /root/

- name: pm2 startup for restart
  command:
    cmd: 'pm2 startup'

- name: pm2 save
  command:
    cmd: 'pm2 save'

- name: Create /var/www/challenges directory
  ansible.builtin.file:
    path: /var/www/challenges
    state: directory
    owner: "root"
    group: "root"
    mode: 0755

- name: Create /etc/ssl/caddy directory
  ansible.builtin.file:
    path: /etc/ssl/caddy
    state: directory
    owner: "root"
    group: "root"
    mode: 0700