- name: Add postgresql sources
  shell: sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

- name: Add apt key for postgres
  shell: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -

- name: Install PostgreSQL 14 from apt
  apt:
    update_cache: yes
    install_recommends: true
    state: latest
    name:
      - postgresql-server-dev-14
      - postgresql-client-14
      - postgresql-contrib
      - python3-psycopg2

- name: Restart and enable postgresql service
  systemd:
    name: postgresql
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: Create a new database with name "origin"
  community.postgresql.postgresql_db:
    name: origin
  become: true
  become_method: su
  become_user: postgres

- name: Create origin user, and grant access to database and table
  community.postgresql.postgresql_user:
    db: '{{db_name}}'
    name: '{{ db_user }}'
    password: '{{ db_password }}'
    expires: "Jan 31 2420"
  become: true
  become_method: su
  become_user: postgres

- name: Grant all privileges on schema public to origin user
  community.postgresql.postgresql_query:
    query: "GRANT ALL ON SCHEMA public TO origin;"
    db: origin
  become: true
  become_method: su
  become_user: postgres
