- name: Add postgresql sources
  shell: sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

- name: Add apt key for postgres
  shell: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -


- name: Install PostgreSQL 14 from apt
  apt:
    update_cache: true
    install_recommends: true
    state: latest
    name:
      - postgresql-server-dev-14
      - postgresql-client-14
      - postgresql-contrib

# caddy service managment

- name: Enabling postgresql service and ensure it is not masked
  systemd:
    name: postgresql
    enabled: yes    

- name: Restart postgresql service, in all cases, also issue daemon-reload to pick up config changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: postgresql

- name: Create a new database with name "origin"
  community.postgresql.postgresql_db:
    name: origin
  become: true
  become_method: su
  become_user: postgres

- name: Create origin user, and grant access to database and table
  community.postgresql.postgresql_user:
    db: origin
    name: origin
    password: '{{ postgres_password }}'
    expires: "Jan 31 2420"
  become: true
  become_method: su
  become_user: postgres

  - name: Grant all privileges on schema public to origin user
  community.general.postgresql_privs:
    database: origin
    schema: public
    state: present
    privs: ALL
    type: schema
    role: origin
  become: true
  become_method: su
  become_user: postgres
