- name: Validate install option input
  fail:
    msg: "Invalid install option selected: {{ selected_install_option }}"
  when: selected_install_option not in ['1', '0']

- name: 
  set_fact:
    install_option: 'origin'
  when: selected_install_option == '0'

- name: 
  set_fact:
    install_option: 'edge'
  when: selected_install_option == '1'

- name:
  pause:
    prompt: "Do you want to use the server in testing mode? (yes/no) [no]: "
    echo: yes
  register: testing_mode
  when: install_option == 'origin'

- name:
  pause:
    prompt: "\nEnter your postgresql password"
    echo: no
  register: postgres_password
  when: install_option == 'origin'

- name:
  pause:
    prompt: "\nEnter your provider wallet address. (The one with the staking)"
    echo: no
  register: public_key
  when: install_option == 'origin'

- name:
  pause:
    prompt: "\nEnter your wallet private key for resource(s) decrypt. This should match the public encryption key provided on the app. (It may or may not be the same as the staking one for security reasons)."
    echo: no
  register: private_key
  when: install_option == 'origin'

- name:
  pause:
    prompt: "\nEnter your wallet public key"
    echo: no
  register: wallet_address
  when: install_option == 'edge'

- name:
  pause:
    prompt: "\nEnter your wallet network"
    echo: no
  register: wallet_network
  when: install_option == 'edge'

- name:
  pause:
    prompt: "\nEnter your server disk space capability in Gigabytes"
  register: disk_space
  when: install_option == 'edge'

- name:
  pause:
    prompt: "\nEnter your server cpu cores capability"
  register: cpu_cores
  when: install_option == 'edge'

- name:
  pause:
    prompt: "\nEnter your server system ram capability in Gigabytes"
  register: system_ram
  when: install_option == 'edge'

- name:
  pause:
    prompt: "\nEnter the IP addresses of your media origins separated by comma"
  register: media_origins_input
  when: install_option == 'edge'

- name:
  set_fact:
    media_origins: "{{media_origins_input.user_input.split(',')}}"

- name:
  pause:
    prompt: "\nEnter the origin's public ssh key"
    echo: no
  register: public_ssh_key
  when: install_option == 'edge'