

- name: Prepare the system for Media-Edge
  file:
    state: absent
    path: /usr/share/keyrings/elasticsearch-keyring.gpg

- name: Adding elasticsearch keyring
  shell: |
    wget -O - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | tee /etc/apt/sources.list.d/elastic-8.x.list

- name: Install and configure Origin stats 
  block:
    - name: Installing Elastic Stack
      apt:
        update_cache: yes
        install_recommends: true
        state: latest
        name:
          - elasticsearch
          - logstash
          - kibana

    - name: Configure Elasticsearch
      template:
        src: files/origin/elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml

    - name: Configure Logstash
      template:
        src: files/origin/logstash.conf.j2
        dest: /etc/logstash/conf.d/logstash.conf

    - name: Configure Kibana
      template:
        src: files/origin/kibana.yml.j2
        dest: /etc/kibana/kibana.yml

    - name: Force stop Java programs if running (may fail, ignore is ok)
      shell: |
        pkill -9 -u elasticsearch
        pkill -9 -u logstash
      ignore_errors: true

    - name: Start and enable Elasticsearch service
      systemd:
        name: elasticsearch
        state: restarted
        enabled: yes

    - name: Start and enable Logstash service
      systemd:
        name: logstash
        state: restarted
        enabled: yes

    - name: Start and enable Kibana service
      systemd:
        name: kibana
        state: restarted
        enabled: yes
  when: inventory_hostname in groups["origin"]

- name: Install and configure Edge stats 
  block:
    - name: Install Filebeat
      apt:
        update_cache: yes
        install_recommends: true
        state: latest
        name: filebeat

    - name: Configure Filebeat
      template:
        src: files/edge/filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
      vars:
        origin_ip: "{{ hostvars[groups['origin'][0]]['ansible_host'] }}"

    - name: Start and enable Filebeat service
      systemd:
        name: filebeat
        state: restarted
        enabled: yes
  when: inventory_hostname in groups["edge"]