# - name: Cleaning up cron if necessary
#   shell: crontab -r
#   ignore_errors: true

- name: Fixing apt package issues
  shell: |
    sed -i '/Acquire::AllowReleaseInfoChange::Suite/d' /etc/apt/apt.conf.d/90releaseinfo-change
    echo 'Acquire::AllowReleaseInfoChange::Suite "true";' >> /etc/apt/apt.conf.d/90releaseinfo-change

- name: Updating apt package
  shell: apt-get update -y --allow-releaseinfo-change

- name: Reconfigure dpkg
  command: dpkg --configure -a

- name: Upgrading system packages
  apt:
    upgrade: "yes"
    update_cache: yes

- name: Preventing services to start after installed
  shell: |
    echo '#!/bin/sh' > /usr/sbin/policy-rc.d
    echo 'exit 101' >> /usr/sbin/policy-rc.d
    chmod +x /usr/sbin/policy-rc.d

- name: Removing potential conflicting packages
  apt:
    state: absent 
    autoremove: true
    name:
      - apache2
      - nginx    
      # - exim4
      # - exim4-base   
      # - exim4-config
      # - exim4-daemon-light       
      # - rpcbind  
      # - nfs-server
      # - libunbound8

- name: Installing shared system packages
  apt:
    update_cache: yes
    install_recommends: true
    state: latest
    name:
      - htop
      - gpg
      - rsync
      - tmux
      - jq
      - wget
      - curl
      - bmon
      - iftop
      #- git
      #- vim
      #- gcc
      #- build-essential
      #- net-tools
      #- python3-pycurl
      #- python3-apt
      #- dnsutils
      #- debian-keyring
      #- debian-archive-keyring
      #- apt-transport-https
      #- gnupg2
      #- libedit-dev
      #- libjemalloc-dev
      #- libncurses-dev
      #- libtool
      #- pkg-config
      #- ethtool
      #- lsb-release

# - name: Installing Edge system packages
#   apt:
#     update_cache: true
#     install_recommends: true
#     state: latest
#     name:
#       - fzf
#       - python3-docutils
#       - python3-sphinx
#   when: inventory_hostname in groups["edge"]

# - name: Installing Origin system packages
#   apt:
#     update_cache: true
#     install_recommends: true
#     state: latest
#     name:
#       - libunbound-dev
#       - software-properties-common
#       - dirmngr
#       - locate
#       - unzip
#       - autotools-dev
#       - libpcre2-dev
#       - cpio
#       - graphviz
#       - autoconf-archive
#       - libpcre3
#   when: inventory_hostname in groups["origin"]

- name: Adds hostname to /etc/hostname based on IP
  shell: |
    echo "{{ 'media-origin-' if inventory_hostname in groups["origin"] else 'media-edge-' }}$(wget -q whatismyip.akamai.com -O -)" > /etc/hostname.tmp
    sed 's/\./-/g' /etc/hostname.tmp > /etc/hostname
    hostname -F /etc/hostname
