- name: Build varnish
  block:
    - name: Copy Varnish config file
      template:
        src: files/origin/varnish/default.vcl.j2
        dest: /root/containers/default.vcl
      when: inventory_hostname in groups["origin"]

    - name: Copy Varnish config file
      template:
        src: files/edge/varnish/default.vcl.j2
        dest: /root/containers/default.vcl
      when: inventory_hostname in groups["edge"]