- name: Build varnish
  block:
    - name: Copy Varnish config file
      template:
        src: "{{ 'files/origin/varnish/default.vcl.j2' if inventory_hostname in groups['origin'] else 'files/edge/varnish/default.vcl.j2' }}"
        dest: /root/containers/default.vcl