{
 "title": "Disk space consumption evaluation",
 "description": "Media-Edge / Disk Utilization",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "compaction events",
   "type": "graph",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_compactions_total[135s])/135*120"
    }
   ]
  },
  {
   "title": "disk space used (PVC \"prometheus-server\")",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=\"monitoring\",persistentvolumeclaim=\"prometheus-server\"}",
     "legendFormat": "{{persistentvolumeclaim}} usage"
    },
    {
     "expr": "prometheus_tsdb_retention_limit_bytes",
     "legendFormat": "Retention"
    }
   ]
  },
  {
   "title": "Disk space increase over selected period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=\"monitoring\",persistentvolumeclaim=\"prometheus-server\"}",
     "legendFormat": "{{persistentvolumeclaim}} usage"
    }
   ]
  },
  {
   "title": "Disk space increase per hour, over selected period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "delta(kubelet_volume_stats_used_bytes{namespace=\"monitoring\",persistentvolumeclaim=\"prometheus-server\"}[${__range_s}s])*3600/${__range_s}",
     "legendFormat": "{{persistentvolumeclaim}} usage"
    }
   ]
  },
  {
   "title": "time retention events (OK)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_time_retentions_total[135s])/135*120"
    }
   ]
  },
  {
   "title": "size retention events (abnormal)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_size_retentions_total[135s])/135*120"
    }
   ]
  }
 ]
}