- name: Create program directory
  file:
    path: /root/guard
    state: directory

- name: Copy program folder
  copy:
    src: ../guard/
    dest: /root/guard

- name: Create .env file
  copy:
    dest: "/root/guard/config/env.js"
    content: |
      module.exports = {
        WALLET: "{{public_key}}",
        PRIVATE_KEY: "{{private_key}}",
        dbstring: "postgres://guard:{{postgres_password}}@127.0.0.1:5432/guard",
        caddyUrl: "http://127.0.0.1:2020/",
        host: "medianetwork.app", // dev
        hns: "medtv", // dev
      }

- name: Run yarn install in program folder
  command: yarn install
  args:
    chdir: /root/guard/

- name: Copy ecosystem file for pm2
  ansible.builtin.copy:
    src: files/guard_files/pm2/ecosystem.config.js
    dest: /root/
    follow: no

- name: Start pm2 from ecosystem
  command:
    cmd: 'pm2 start ecosystem.config.js'
    chdir: /root/

- name: pm2 startup for restart
  command:
    cmd: 'pm2 startup'

- name: pm2 save
  command:
    cmd: 'pm2 save'