# Usa una imagen base de Node.js
FROM node:18

# Crea el directorio de la aplicación
WORKDIR /usr/src/app

# Copia los archivos de la aplicación
COPY package*.json ./

RUN npm install --omit=dev

USER node

COPY --chown=node:node . ./

# Compila el código TypeScript
RUN npm run build

# Exponer el puerto de la aplicación
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["npm", "run", "start"]