FROM caddy:2.8

# Copia los archivos de configuración
COPY ./caddy /usr/local/bin/caddy
RUN chmod +x /usr/local/bin/caddy

# Exponer el puerto 80 y 443
EXPOSE 80 443 2020

# Comando para arrancar Caddy con la configuración especificada
CMD ["/usr/local/bin/caddy", "run", "--environ", "--config", "/etc/caddy/Caddyfile"]