# Usa una imagen base de Caddy para la ejecución
FROM caddy:2.8

COPY ./caddy /usr/bin/caddy
RUN chmod +x /usr/bin/caddy

# Exponer el puerto 80 y 443
EXPOSE 80 443 2020

# Comando para iniciar Caddy
CMD ["/usr/bin/caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]