FROM varnish:6.6

# Crea el directorio de caché y establece los permisos
RUN mkdir -p /var/cache/varnish && chown varnish:varnish /var/cache/varnish

# Configura el comando de inicio para usar espacio en disco para la caché
CMD ["sh", "-c", "varnishd -F -a 0.0.0.0:6969 -T localhost:6082 -f /etc/varnish/default.vcl -s file,/var/cache/varnish/varnish.cache,${CACHE_SIZE}"]